---
- name: Playbook to ensure base software is installed.
  hosts: linux
  become: true
  tasks: 
  - name: Ansible apt install neofetch
    apt:
      name:
        - nano
        - neofetch
        - tree
      state: present
      update_cache: yes # Simulate apt-update on the first run.
