---
- name: Playbook to prepare Proxmox VMs.
  hosts: proxmox_vms
  become: true
  tasks: 
  - name: Ansible apt install qemu-guest-agent
    apt:
      name: qemu-guest-agent
      state: present
      update_cache: yes # Simulate apt-update on the first run.
