services:

  ghost_app:
    image: ghost:5-alpine
    restart: always
    ports:
      - 9095:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: ghost
      database__connection__password: <replacewithasecurelygeneratedpassword>
      database__connection__database: ghost_db
      mail__transport: SMTP
      mail__options__service: Google
      mail__options__host: smtp.gmail.com
      mail__options__port: 465
      mail__options__secure: true
      mail__options__auth__user: sofmeright@gmail.com
      mail__options__auth__pass: <replacewithasecurelygeneratedpassword>
      mail__from: sofmeright@gmail.com
      mail__options__secure_connection: true
      privacy__useUpdateCheck: true
      privacy__useGravatar: true
      privacy__useRpcPing: true
      privacy__useStructuredData: true
      # this url value is just an example, and is likely wrong for your environment!
      url: https://blog.sofmeright.com/
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - /mnt/app_data/Server/Web-App/_docker-stack/ghost/data:/var/lib/ghost/content
    depends_on:
    - ghost_db
    links:
    - ghost_db

  ghost_db:
    container_name: ghost_db
    image: mysql:8.0
    restart: always
    environment:
    - MYSQL_DATABASE=ghost_db
    - MYSQL_USER=ghost
    - MYSQL_PASSWORD=<replacewithasecurelygeneratedpassword>
    - MYSQL_ROOT_PASSWORD=<replacewithasecurelygeneratedpassword>
    - MYSQL_ROOT_HOST=%
    volumes:
      - /mnt/app_data/Server/Web-App/_docker-stack/ghost/mysql:/var/lib/mysql